title: Festus Aigbedion # Your name (or website title) here
logo: "/Images/mypics.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Making meaning out of numbers and painting stories with graphics is my passion.
  I see things mostly from a data point of view.
  I hold a Bachelors degree in Applied Statistics with strong passion for analysis.  
theme: jekyll-theme-minimal
